import { DOCUMENT, isPlatformBrowser } from '@angular/common';
import {
  computed,
  DestroyRef,
  inject,
  PLATFORM_ID,
  resource,
  ResourceLoaderParams,
  ResourceRef,
  signal,
  WritableSignal,
} from '@angular/core';
import { ArchitectureSummary, ModelInfo, NeuralNetworkLayers, TestResult } from './model-info';

/**
 * Minimal contract for any WASM-backed neural network instance.
 * All concrete network classes generated by wasm-bindgen must satisfy this.
 */
export interface WasmNetwork {
  /** Free WASM memory for this instance. */
  free(): void;
  /** Returns JSON-encoded model metadata. */
  model_info(): string;
  /** Returns JSON-encoded architecture summary. */
  get_architecture(): string;
  /** Returns JSON-encoded layer weights and biases. */
  get_weights(): string;
  /** Returns JSON-encoded test results. */
  test_all(): string;
}

/**
 * Abstract base class for all WASM neural network services.
 *
 * Provides shared WASM loading, lifecycle management, and reactive computed signals.
 * Concrete services extend this class and supply only the WASM-specific glue:
 * the binary path, the init function, and the network constructor.
 *
 * @typeParam TNetwork - The concrete WASM network class (must satisfy WasmNetwork).
 * @typeParam TInitOutput - The InitOutput type from the WASM module.
 */
export abstract class BaseWasmService<TNetwork extends WasmNetwork, TInitOutput> {
  private readonly _document = inject(DOCUMENT);
  private readonly _platformId = inject(PLATFORM_ID);
  private readonly _destroyRef = inject(DestroyRef);

  protected readonly _wasmPath: WritableSignal<string> = signal('');

  /** Cached network instance — reused across computed re-evaluations. */
  private _networkInstance: TNetwork | null = null;

  constructor() {
    const base = this.resolveWasmBase();
    this._wasmPath.set(this.wasmFilePath(base));
    this._destroyRef.onDestroy(() => this.dispose());
  }

  // ---------------------------------------------------------------------------
  // Abstract hooks — must be implemented by concrete services
  // ---------------------------------------------------------------------------

  /**
   * Returns the absolute WASM binary path for this module.
   * @param base - Base URL (e.g. "/" or the Angular <base href> value).
   */
  protected abstract wasmFilePath(base: string): string;

  /**
   * Loads the WASM module from the given path.
   * Should call the module-level `init({ module_or_path })` generated by wasm-bindgen.
   */
  protected abstract loadModule(path: string): Promise<TInitOutput>;

  /**
   * Creates and returns a new instance of the WASM network class.
   * Called once, lazily, after the module has loaded.
   */
  protected abstract createNetwork(): TNetwork;

  // ---------------------------------------------------------------------------
  // Lifecycle
  // ---------------------------------------------------------------------------

  /**
   * Releases the cached WASM network instance and frees its memory.
   * Called automatically when the service is destroyed.
   */
  public dispose(): void {
    if (this._networkInstance) {
      try {
        this._networkInstance.free();
      } catch {
        // Ignore errors if the instance was already freed.
      }
      this._networkInstance = null;
    }
  }

  // ---------------------------------------------------------------------------
  // Private helpers
  // ---------------------------------------------------------------------------

  private resolveWasmBase(): string {
    if (!isPlatformBrowser(this._platformId)) {
      return '/';
    }
    const b = this._document.querySelector('base')?.getAttribute('href') ?? '/';
    if (b === './') return './';
    return b.endsWith('/') ? b : b + '/';
  }

  // ---------------------------------------------------------------------------
  // Public reactive API (shared across all WASM services)
  // ---------------------------------------------------------------------------

  /** Resource managing WASM module loading state. */
  public readonly wasmResource: ResourceRef<TInitOutput | undefined> = resource({
    params: this._wasmPath,
    loader: (param: ResourceLoaderParams<string>) => this.loadModule(param.params),
    defaultValue: undefined,
  });

  /** Network instance, available after the WASM module has loaded. */
  public readonly network = computed(() => {
    const initOutput = this.wasmResource.value();
    if (!initOutput) return undefined;
    if (!this._networkInstance) {
      this._networkInstance = this.createNetwork();
    }
    return this._networkInstance;
  });

  /** Model metadata (name, accuracy, architecture string, description). */
  public readonly modelInfo = computed(() => {
    const network = this.network();
    if (!network) return undefined;
    return JSON.parse(network.model_info()) as ModelInfo;
  });

  /** Architecture summary in unified format (all models). */
  public readonly architectureSummary = computed(() => {
    const network = this.network();
    if (!network) return undefined;
    return JSON.parse(network.get_architecture()) as ArchitectureSummary;
  });

  /**
   * Network architecture as a parsed array of layer sizes.
   * Handles plain numbers, CNN-prefixed strings (e.g. "CNN(LeNet-5)"),
   * and multi-channel layer descriptors ("[16,28,28]").
   */
  public readonly architecture = computed(() => {
    const modelInfo = this.modelInfo();
    if (!modelInfo) return undefined;
    return modelInfo.architecture.split('→').map((layer) => {
      const trimmedLayer = layer.trim();
      if (trimmedLayer.startsWith('[') && trimmedLayer.endsWith(']')) {
        return trimmedLayer
          .slice(1, -1)
          .split(',')
          .map((n) => Number(n.trim()));
      }
      const num = Number(trimmedLayer);
      return isNaN(num) ? trimmedLayer : num;
    });
  });

  /** Layer weights and biases for all FC layers. */
  public readonly weights = computed(() => {
    const network = this.network();
    if (!network) return undefined;
    return JSON.parse(network.get_weights()) as NeuralNetworkLayers;
  });

  /** Test results for validation samples. */
  public readonly testAll = computed(() => {
    const network = this.network();
    if (!network) return undefined;
    return JSON.parse(network.test_all()) as TestResult[];
  });
}
