fn main() {
    println!("╔══════════════════════════════════════════════════════════════╗");
    println!("║            Neural Network Library — Rust                     ║");
    println!("╚══════════════════════════════════════════════════════════════╝");
    println!();
    println!("Workspace crates:");
    println!("  cma-neural-network  — Dense networks, training, metrics, serialization");
    println!("  cma-cnn             — CNN inference pipeline (Conv2D, Pool, BN, ...)");
    println!("  cma-autograd        — Automatic differentiation + CNN training");
    println!("  cma-models          — Pre-built architectures (LeNet, ResNet, VGG, ...)");
    println!();
    println!("─── cma-neural-network ─────────────────────────────────────────");
    println!("  • NetworkBuilder / TrainingBuilder  — fluent construction API");
    println!("  • 15 activations  (ReLU, GELU, Mish, Swish, Tanh, Sigmoid, ...)");
    println!("  • 5  loss functions (MSE, MAE, BCE, CCE, Huber)");
    println!("  • 5  optimizers   (SGD, Momentum, RMSprop, Adam, AdamW)");
    println!("  • Regularization  (Dropout, L1, L2, ElasticNet)");
    println!("  • 6  LR schedules (Step, Cosine, Warmup, Cyclic, Exponential, ...)");
    println!("  • Callbacks       (EarlyStopping, ModelCheckpoint, ProgressBar)");
    println!("  • Metrics         (accuracy, precision, recall, F1, ROC/AUC)");
    println!("  • Serialization   (JSON + binary)");
    println!();
    println!("─── cma-cnn ────────────────────────────────────────────────────");
    println!("  • Conv2D, DepthwiseConv2D, MaxPool2D, AvgPool2D, GlobalAvgPool2D");
    println!("  • BatchNorm2D, Dropout2D, Flatten, ActivationLayer");
    println!("  • Sequential builder  — forward / forward_batches / intermediates");
    println!("  • Static shape inference  — TensorShape arithmetic");
    println!();
    println!("─── cma-autograd ───────────────────────────────────────────────");
    println!("  • Tensor with requires_grad + backward()");
    println!("  • Linear, Conv2D modules");
    println!("  • CnnBuilder presets  (lenet5, alexnet_mnist, vgg_mnist, resnet_mnist)");
    println!("  • SGD / Adam optimizers");
    println!("  • CnnTrainer  — fit() with train/val loss tracking");
    println!();
    println!("─── cma-models ─────────────────────────────────────────────────");
    println!("  • LeNet5, ResNet (18/34/50), VGG16/19, AlexNet, EfficientNetB0");
    println!("  • All forward() return feature vectors — wire your own FC head");
    println!();
    println!("Examples  (cargo run --example <name>):");
    println!("  getting_started     ← start here  (dense network, full tour)");
    println!("  metrics_demo        — accuracy, F1, confusion matrix, ROC/AUC");
    println!("  serialization       — JSON & binary save/load");
    println!("  minibatch_demo      — batch training strategies + benchmarks");
    println!("  cnn_inference       — cma-cnn Sequential pipeline");
    println!("  autograd_training   — cma-autograd end-to-end CNN training");
    println!();
    println!("Usage guides:  docs/guides/");
    println!("  01-quickstart.md        04-autograd-training.md");
    println!("  02-dense-network.md     05-models.md");
    println!("  03-cnn-inference.md");
}